### ISSUE TITLE
Drum Kit challenge

### ISSUE THREAD

**Issue by Aditya-chaki** [KapilKumar7/Hacktoberfest2022-masai#18]
@KapilKumar7 Kindly assign me this under Hacktoberfest 2022.

**Comment by KapilKumar7** [comment]
Can you please elaborate more about this challenge, How you will gonna add Drumstick to this project?

**Comment by Aditya-chaki** [comment]
@KapilKumar7 In this project , by pressing different keys from keyboard , it produces different types of drum sounds .

**Comment by KapilKumar7** [comment]
But we have just readme the file, We still don't have deployed that project on the web, then where will these sounds produce? On which part you are thinking of adding these sounds ?

**Comment by Aditya-chaki** [comment]
Sir , in readme file we can ellaborate this project and by adding picture of my project we can explain the project clearly.

**Comment by KapilKumar7** [comment]
You can work on this by forking the repo and Let me show some work (by attaching some screenshots) on that,  If it can be added to our repo then I will definitely Merge the code with the main codebase. Thanks.
