### ISSUE TITLE
for contribution

### ISSUE THREAD

**Issue by ayush4345** [KapilKumar7/Hacktoberfest2022-masai#28]
what you want us to contribute to this repo.

**Comment by KapilKumar7** [comment]
This is simply an Opensource beginner project, where You can Add your name to the readme file in the list of coders alphabetically as mentioned in the readme, You can suggest more improvements for the Project as well. For simple video instruction 
refer to this link->https://www.linkedin.com/feed/update/urn:li:activity:6985569051586490368/
