### ISSUE TITLE
Enhancement of Readme file

### ISSUE THREAD

**Issue by payallenka** [KapilKumar7/Hacktoberfest2022-masai#52]
I would like to add an image containing an empowering quote which would motivate other programmers who go through your file.
This will be located at the end of the readme file - after the list of contributors. 
I wish to participate in hacktoberfest. So it will be really great if you add the hactoberfest tag to this issue/enhancement.

**Comment by KapilKumar7** [comment]
@payallenka Thanks, Go ahead you can work on it.
